version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: next-pwa
    versions:
    - 5.1.4
    - 5.2.1
    - 5.2.14
    - 5.2.3
    - 5.2.5
    - 5.2.9
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.7
    - 6.2.8
  - dependency-name: "@storybook/react"
    versions:
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.7
    - 6.2.8
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.19.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.20.0
    - 4.21.0
  - dependency-name: next
    versions:
    - 10.1.1
  - dependency-name: "@babel/core"
    versions:
    - 7.13.13
  - dependency-name: "@types/node"
    versions:
    - 14.14.36
    - 14.14.37
